### ISSUE TITLE
Please include code in repo

### ISSUE THREAD

**Issue by jacksongoode** [soulhotel/Vertical-Tabs-Firefox-CSS#1]
Not just in a release.zip.

**Comment by soulhotel** [comment]
You just reminded me that I should update this :).<br>
Source added to Repo.<br>

<details>
<summary>(Click me) Repo Updates, optimization updates, bug fixes, support for 'unload tab' extensions</summary>
pin unpin, containers, drag to new window, free up sidebar, themes support
  
![functionality](https://github.com/soulhotel/Vertical-Tabs-Firefox-CSS/assets/155501797/46b0c09b-0599-4e5a-8af8-1cb0ad3255fb)
</details>
<details>
<summary>(Click me) auto-hide tabs options (overlay content or push content to side), and more</summary>

![autohide 1](https://github.com/soulhotel/Vertical-Tabs-Firefox-CSS/assets/155501797/28471586-47b8-4c6b-bf8e-6c60dba21e79)
![autohide 2](https://github.com/soulhotel/Vertical-Tabs-Firefox-CSS/assets/155501797/0e556e81-c6e9-4d75-9cb9-5629a8ced99e)
</details>
