### ISSUE TITLE
no close button

### ISSUE THREAD

**Issue by Momossim** [soulhotel/Vertical-Tabs-Firefox-CSS#3]
as opposed to your demo, i don't have a close button (see image below) (i didn't touch anything in the config btw)
![image](https://github.com/soulhotel/Vertical-Tabs-Firefox-CSS/assets/87722139/8398a35c-598e-41d7-80d4-a26714c4957d)

**Comment by Ahamed07** [comment]
if you are using sidebery then go to settings and turn on show close button 

if you are using the ff-ultima verticle tab go to about:config > search ultima.tabs.closetabsbutton change it to true

**Comment by Momossim** [comment]
oh ok now it works thanks
